# Generated by Django 5.1 on 2024-10-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.CharField(default='https://www.juliedray.com/wp-content/uploads/2022/01/sans-affiche.png', max_length=500),
        ),
    ]
