# Generated by Django 5.1.1 on 2024-10-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieSite', '0002_moviedata_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/none/nothing.jpg', upload_to='images/'),
        ),
    ]
