# Generated by Django 5.1.1 on 2024-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieSite', '0003_moviedata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/coming_soon.jpg', upload_to='images/'),
        ),
    ]
