# Generated by Django 5.1.3 on 2024-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(max_length=500),
        ),
    ]
