# Generated by Django 5.1 on 2024-10-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_image/profile_img.jpg.jpg', upload_to='profile_image/'),
        ),
    ]
